### ISSUE TITLE
Log level affects Z3 behavior

### ISSUE THREAD

**Issue by s0mark** [ftsrg/theta#246]
Running Theta in different log level configurations leads to `Z3Exception` for certain log levels, while resulting in successful verification for others.

**Theta version:** [b56a6ac](https://github.com/s0mark/theta/tree/b56a6ac0b046c320d06a6c3f996def849e89864a)
**Input task:** [recursive-simple/id2_b3_o2.c](https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/recursive-simple/id2_b3_o2.c?ref_type=heads)
**Configuration:** `--domain PRED_CART
--refinement BW_BIN_ITP
--search BFS
--lbe NO_LBE`
**Platform:** MacOS 10.15

Results based on log level setting:
| `loglevel` | verification | result |
| :--------: | :----------: | :-----------: |
|  `RESULT`  |      ✅       |    unsafe     |
| `MAINSTEP` |      ✅       |    unsafe     |
| `SUBSTEP`  |      ✅       |    unsafe     |
|   `INFO`   |      ✅       |    unsafe     |
|  `DETAIL`  |      ❌       |`Z3Exception` |
| `VERBOSE`  |      ❌       | `Z3Exception` |

**Stack trace:**
```java
com.microsoft.z3.Z3Exception: not an inequality
	at com.microsoft.z3.Native.getInterpolant(Native.java:5468)
	at com.microsoft.z3.InterpolationContext.GetInterpolant(InterpolationContext.java:91)
	at hu.bme.mit.theta.solver.z3.Z3ItpSolver.getInterpolant(Z3ItpSolver.java:105)
	at hu.bme.mit.theta.analysis.expr.refinement.ExprTraceBwBinItpChecker.check(ExprTraceBwBinItpChecker.java:125)
	at hu.bme.mit.theta.analysis.expr.refinement.SingleExprTraceRefiner.refine(SingleExprTraceRefiner.java:94)
	at hu.bme.mit.theta.xcfa.analysis.XcfaSingleExprTraceRefiner.refine(XcfaSingeExprTraceRefiner.kt:73)
	at hu.bme.mit.theta.analysis.algorithm.cegar.CegarChecker.check(CegarChecker.java:106)
	at hu.bme.mit.theta.xcfa.cli.XcfaCegarConfig.check(XcfaCegarConfig.kt:188)
	at hu.bme.mit.theta.xcfa.cli.XcfaCli$runDirect$1.invoke(XcfaCli.kt:311)
	at hu.bme.mit.theta.xcfa.cli.XcfaCli$runDirect$1.invoke(XcfaCli.kt:311)
	at hu.bme.mit.theta.xcfa.cli.ExitCodesKt.exitOnError(ExitCodes.kt:56)
	at hu.bme.mit.theta.xcfa.cli.XcfaCli.runDirect(XcfaCli.kt:311)
	at hu.bme.mit.theta.xcfa.cli.XcfaCli.run(XcfaCli.kt:263)
	at hu.bme.mit.theta.xcfa.cli.XcfaCli.access$run(XcfaCli.kt:83)
	at hu.bme.mit.theta.xcfa.cli.XcfaCli$Companion.main(XcfaCli.kt:615)
	at hu.bme.mit.theta.xcfa.cli.XcfaCli.main(XcfaCli.kt)
Process failed! (hu.bme.mit.theta.solver.z3.Z3ItpSolver.getInterpolant(Z3ItpSolver.java:105), com.microsoft.z3.Z3Exception: not an inequality)
```

**Comment by csanadtelbisz** [comment]
Could you re-test the issue if it is still there @s0mark?

**Comment by s0mark** [comment]
Sorry for the late reply!

Theta v7.0.1 can't solve this task anymore in this configuration, the CEX monitor shuts it down. Disabling it reveals different behavior for the old and new Z3:
- old Z3: nondeterministically either fails with `Unsupported function '@contra' in Z3 back-transformation` or times out around the 80th iteration
- new Z3: iterates indefinitely with about 500 iterations per second

Both produce these behaviors regardless of the log level. The issue has thus become irrelevant, therefore, I'm closing it.
