### ISSUE TITLE
NPE in Z3TermTransformer with SEQ_ITP and bitvectors

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/theta#89]
Running Theta v2.5.0 on ` subprojects/cfa-analysis/src/test/resources/counter_bv_true.cfa` gives a NPE. This should be fixed, or if there is some unsupported feature a more informative error message should be given.

```
$ java -jar subprojects/cfa-cli/build/libs/theta-cfa-cli-2.5.0-all.jar --model subprojects/cfa-analysis/src/test/resources/counter_bv_true.cfa --stacktrace
Iteration 1
| Checking abstraction...
|  |  (Re)initializing ARG...done
|  |  Building ARG...done
| Checking abstraction done, result: (AbstractorResult Unsafe)
| Refining abstraction...
|  |  Checking trace...Exception occurred, message: Error while running algorithm: null
Trace:
java.lang.Exception: Error while running algorithm: null
        at hu.bme.mit.theta.cfa.cli.CfaCli.check(CfaCli.java:230)
        at hu.bme.mit.theta.cfa.cli.CfaCli.run(CfaCli.java:186)
        at hu.bme.mit.theta.cfa.cli.CfaCli.main(CfaCli.java:146)
Caused by: java.lang.NullPointerException
        at hu.bme.mit.theta.solver.z3.Z3TermTransformer.toFuncLitExpr(Z3TermTransformer.java:120)
        at hu.bme.mit.theta.solver.z3.Z3TermTransformer.transformApp(Z3TermTransformer.java:223)
        at hu.bme.mit.theta.solver.z3.Z3TermTransformer.transform(Z3TermTransformer.java:167)
        at hu.bme.mit.theta.solver.z3.Z3TermTransformer.lambda$exprUnaryOperator$2(Z3TermTransformer.java:394)
        at hu.bme.mit.theta.solver.z3.Z3TermTransformer.transformApp(Z3TermTransformer.java:217)
        at hu.bme.mit.theta.solver.z3.Z3TermTransformer.transform(Z3TermTransformer.java:167)
        at hu.bme.mit.theta.solver.z3.Z3TermTransformer.toExpr(Z3TermTransformer.java:115)
        at hu.bme.mit.theta.solver.z3.Z3ItpSolver.getInterpolant(Z3ItpSolver.java:101)
        at hu.bme.mit.theta.analysis.expr.refinement.ExprTraceSeqItpChecker.check(ExprTraceSeqItpChecker.java:97)
        at hu.bme.mit.theta.analysis.expr.refinement.SingleExprTraceRefiner.refine(SingleExprTraceRefiner.java:72)
        at hu.bme.mit.theta.analysis.algorithm.cegar.CegarChecker.check(CegarChecker.java:87)
        at hu.bme.mit.theta.cfa.analysis.config.CfaConfig.check(CfaConfig.java:39)
        at hu.bme.mit.theta.cfa.cli.CfaCli.check(CfaCli.java:228)
        ... 2 more

```

**Comment by hajduakos** [comment]
As far as I saw, the problem is that Z3 actually returns an interpolant, which has `(bvule #x5 |_x:1_0|)`, where `bvule` is a function application. The transformer cannot get the function `bvule` from the symbol table so it tries to get it as a literal from the model, which does not exist.

**Comment by as3810t** [comment]
Yes, Z3TermTransformer does not implement transformations for bitvector operations, as interpolation with bitvectors rarely succeeds.

In my experience, Z3 can handle interpolation with simple formulas, but not with complex ones (when there are arrays present, etc...).

**Comment by hajduakos** [comment]
I see, that's completely reasonable. But can we add a more informative error message? Like "Function bvule not found in table and model, probably an unsupported function"?

**Comment by as3810t** [comment]
Yes, that can be easily implemented.
